name: CI

on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:

jobs:
  
  test:
    strategy:
      fail-fast: true
      matrix:
        os: [ "ubuntu-latest" ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pip
        run: python -m pip install --upgrade pip
      - name: Install package + other dependencies
        run: |
          pip install "autostep @ git+https://github.com/UBC-Stat-ML/autostep.git"
          pip install . 
          pip install coverage
      - name: Run tests
        run: |
          python -m coverage run -m unittest
          python -m coverage xml
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          file: ./coverage.xml
